spring.application.name=portfolio-manager

spring.datasource.url=jdbc:postgresql://localhost:5432/pm_db
spring.datasource.username=pm_user
spring.datasource.password=rT8$wQ2!Zf6@N#yP4^mL7&cX

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.web.error.include-message=always