spring.application.name=portfolio-manager

spring.datasource.url=jdbc:postgresql://localhost:5432/pm_db
spring.datasource.username=pm_user
spring.datasource.password=${PM_DB_PWD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.flyway.url=jdbc:postgresql://localhost:5432/pm_db
spring.flyway.user=pm_admin
spring.flyway.password=${PM_FLYWAY_PWD}
spring.flyway.schemas=pm
spring.flyway.default-schema=pm

spring.web.error.include-message=always